source "https://rubygems.org"

gem "rails"
gem "puma"
gem "nokogiri"
gem "jekyll"
gem "jekyll-remote-theme"
gem "jekyll-seo-tag"
gem "github-pages", group: :jekyll_plugins
gem "webrick"
gem "just-the-docs"
