name: Test Shiny App Startup

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      RENV_PATHS_ROOT: ~/.cache/R/renv
      
    steps:
    - uses: actions/checkout@v3
    - uses: r-lib/actions/setup-r@v2
      with:
        r-version:4.2.0
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev libsqlite3-dev libglu1-mesa-dev default-jdk libmagick++-dev
        sudo apt install curl
        
    - name: Cache packages
      uses: actions/cache@v2
      with:
        path: ${{ env.RENV_PATHS_ROOT }}
        key: ${{ runner.os }}-renv-${{ hashFiles('**/renv.lock') }}
        restore-keys: |
          ${{ runner.os }}-renv-
          
    - uses: r-lib/actions/setup-renv@v2
    
 #   - name: Restore packages
#      shell: Rscript {0}
#      run: |
#        if (!requireNamespace("renv", quietly = TRUE)) install.packages("renv")
#        renv::restore()

     - name: test specific packages
        run: |
          Rscript -e 'install.packages("Rcpp")'
          Rscript -e 'install.packages("RcppArmadillo")'
          Rscript -e 'install.packages("DESeq2")'

    - name: Test if Shiny app starts
      run: |
        Rscript -e "shiny::runApp('program/shinyApp', launch.browser = FALSE, port = 3838)"
        sleep 10  # Sleep for 10 seconds to ensure the app has time to start
