source("R/version.R",local = T)
source("R/util.R", local = T)
source("R/C.R",local = T)
source("R/fun_filterRNA.R",local = T)
source("R/fun_LFC.R",local = T)
source("R/heatmap/fun_entitieSelection.R",local = T)
source("R/fun_LogIt.R",local = T)
source("R/fun_readInSampleTable.R",local = T)
source("R/fun_getCodeSnippets.R",local = T)
source("R/module_DownloadReport.R",local = T)
source("R/enrichment_analysis/enrichment_analysis.R", local = T)
source("R/enrichment_analysis/overrepresentation_analysis.R", local = T)
source("R/enrichment_analysis/check_annotation.R", local = T)
source("R/enrichment_analysis/translation.R", local = T)
source("R/enrichment_analysis/server.R", local = T)
source("R/heatmap/server.R",local = T)
source("R/pca/server.R", local = T)
source("R/pca/util.R", local = T)
source("R/single_gene_visualisation/server.R",local = T)
source("R/sample_correlation/server.R", local = T)
source("R/sample_correlation/util.R", local = T)
source("R/significance_analysis/server.R", local = T)
source("R/significance_analysis/util.R", local = T)
source("R/pre_processing/util.R", local = T)


